[package]
name = "tamuhack2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.77"
rand = "0.8.5"
rocket = { version = "0.5.0", features = ["secrets"]}
